[build]
  publish = "public"
  command = "rm -rf node_modules/.cache && npm run build"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
